spring.application.name=inji_usecase
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
management.endpoint.health.show-details=always
server.servlet.context-path=/v1/truckpass-usecase

# ===============================================
# = CORS CONFIGURATION
# ===============================================
# Comma-separated list of origins to allow for CORS.
# Example: http://localhost:3000,https://your-prod-domain.com
cors.allowed.origins=http://localhost:3000
management.endpoint.env.show-values=ALWAYS
management.endpoints.web.exposure.include=*