spring.application.name=inji_usecase
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================================
# = CORS CONFIGURATION
# ===============================================
# Comma-separated list of origins to allow for CORS.
# Example: http://localhost:3000,https://your-prod-domain.com
cors.allowed.origins=http://localhost:3000

# Database configuration for Farmer
spring.datasource.url=jdbc:postgresql://localhost:5432/farmer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=farmer