spring.application.name=inji_usecase
server.port=8092
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
management.endpoint.health.show-details=always
server.servlet.context-path=/v1/truckpass

# ===============================================
# = CORS CONFIGURATION
# ===============================================
# Comma-separated list of origins to allow for CORS.
# Example: http://localhost:3000,https://your-prod-domain.com
cors.allowed.origins=http://localhost:3000


# ---- Mail (SMTP production) ----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[email id]
spring.mail.password=[app password]
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

mosip.inji-usecase.products.truckpass.emailField=driverEmailId
mosip.inji-usecase.products.truckpass.template=truckpass
mosip.inji-usecase.products.truckpass.subject=Your Truckpass is Ready - {{truckpassId}}

mosip.inji-usecase.products.farmer.emailField=email
mosip.inji-usecase.products.farmer.template=farmer
mosip.inji-usecase.products.farmer.subject=Welcome Farmer {{name}}

# Truckpass email template
mosip.inji-usecase.templates.email.truckpass=Hello {{driver.name}},\n\nYour truckpass (ID: {{truckpassId}}) for vehicle {{vehicleNumber}} is ready.\n\nRegards,\n{{companyName}}

# Farmer email template
mosip.inji-usecase.templates.email.farmer=Dear {{name}},\n\nThank you for registering with us. Your details have been successfully recorded.\n\nWarm regards,\n{{companyName}}

# From incoming commit
management.endpoint.env.show-values=ALWAYS
management.endpoints.web.exposure.include=*
