# Database configuration for Farmer
spring.farmer-datasource.jdbc-url=jdbc:postgresql://${database.host}:${database.port}/${database.name}?currentSchema=certify
spring.farmer-datasource.username=${database.username}
spring.farmer-datasource.password=${db.dbuser.password}
spring.farmer-datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.properties.hibernate.default_schema=farmer

# Farmer JPA / Hibernate Configuration
spring.farmer.jpa.hibernate.ddl-auto=none
spring.farmer.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.farmer.jpa.show-sql=false
spring.farmer.jpa.properties.hibernate.format_sql=true
spring.farmer.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Database configuration for TruckPass
spring.truckpass-datasource.jdbc-url=jdbc:postgresql://${database.host}:${database.port}/${database.name}?currentSchema=certify
spring.truckpass-datasource.username=${database.username}
spring.truckpass-datasource.password=${db.dbuser.password}
spring.truckpass-datasource.driver-class-name=org.postgresql.Driver

# TruckPass JPA / Hibernate Configuration
spring.truckpass.jpa.hibernate.ddl-auto=none
spring.truckpass.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.truckpass.jpa.show-sql=false
spring.truckpass.jpa.properties.hibernate.format_sql=true
spring.truckpass.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Global JPA / Hibernate Configuration
# Used when no specific datasource is defined for an operation
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
