# Database configuration for Farmer
spring.farmer-datasource.jdbc-url=jdbc:postgresql://localhost:5432/farmer
spring.farmer-datasource.username=postgres
spring.farmer-datasource.password=postgres
spring.farmer-datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=farmer