# Database configuration for Farmer
spring.farmer-datasource.jdbc-url=jdbc:postgresql://localhost:5432/farmer
spring.farmer-datasource.username=postgres
spring.farmer-datasource.password=postgres
spring.farmer-datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.default_schema=farmer
server.port=8080
# Database configuration for TruckPass
spring.truckpass-datasource.jdbc-url=jdbc:postgresql://localhost:5432/truckpass
spring.truckpass-datasource.username=postgres
spring.truckpass-datasource.password=postgres
spring.truckpass-datasource.driver-class-name=org.postgresql.Driver

#entity-datasource
spring.entity-datasource.jdbc-url=jdbc:postgresql://localhost:5432/postgres
spring.entity-datasource.username=postgres
spring.entity-datasource.password=postgres
spring.entity-datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=inji_usecase_generic