name: Maven Package upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - master
      - 1.*
      - develop
      - MOSIP*
      - release*
      - INJICERT*
      - truckpass

jobs:
  build-maven-inji-usecase:
    uses: mosip/kattu/.github/workflows/maven-build.yml@master-java21
    with:
      SERVICE_LOCATION: ./inji-usecase
      BUILD_ARTIFACT: inji-usecase
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    
  build-truckpass-ui:
    uses: mosip/kattu/.github/workflows/npm-build.yml@develop
    with:
      SERVICE_LOCATION: truck-pass
      BUILD_ARTIFACT: truckpass-ui
      NPM_BUILD_TYPE: 'BOB'
      NODE_VERSION: "18.x"
      ZIP_DIR: "build"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers-truckpass-ui:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: truck-pass
            SERVICE_NAME: 'truckpass-ui'
            SQUASH_LAYERS: '16'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      SQUASH_LAYERS: ${{ matrix.SQUASH_LAYERS }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers-inji-usecase:
    needs: build-maven-inji-usecase
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'inji-usecase'
            SERVICE_NAME: 'inji-usecase'
            BUILD_ARTIFACT: 'inji-usecase'
            SQUASH_LAYERS: '15'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master-java21
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      BUILD_ARTIFACT: ${{ matrix.BUILD_ARTIFACT }}
      SQUASH_LAYERS: ${{ matrix.SQUASH_LAYERS }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
